// Generated by CoffeeScript 1.9.3

//var http = require('http');
var express = require('express');
var app = express();
var url = require('url');
var qs = require('querystring');
var sys = require ('sys');
var wav = require('wav');
var Speaker = require('speaker');
var fs = require('fs');
var document = require('document');
var io = require('socket.io-client');
var cors = require('cors');
var corser = require("corser");
app.use(corser.create());
app.post('/', function (req, res) {

//http.createServer(function (req, res) {

//   if(req.method=='POST') {
           var body='';
           req.on('data', function (data) {
               body +=data;
           });
           req.on('end',function(){
               
               //var POST =  qs.parse(body);
               var POST =  JSON.parse(body);
               console.log(POST);
 
var socket = io.connect('http://153.149.33.119:3000');
socket.on('news', function (msg) {
    console.log("newskita");
});

var huga = 0;
var hoge = setInterval(function() {
    makevoice();
    huga++;
    //終了条件
    if (huga == 5) {
    clearInterval(hoge);
    sendmessage();
    }
}, 500);


function sendmessage(){
    var msg = POST;
    socket.emit('sendMsgFromClient', { value: POST.test });
    }

function makevoice() {
  var VoiceText, fs, voice;

  require('register');

  fs = require('fs');

  VoiceText = require('voicetext');

  voice = new VoiceText('jdd58fkejgh09lyb');

  voice.speaker(voice.SPEAKER.HIKARI).speak(POST.test, function(e, buf) {
    if (e) {
      console.error(e);
    }
    return fs.writeFile('/Library/WebServer/Documents/test.wav', buf, 'binary', function(e) {
      if (e) {
        return console.error(e);
      }
    });
  });
  console.log("OK");
}

           });


  setTimeout(function() {
    res.setHeader('Content-Type', 'text/plain');
    res.writeHead(200);
    res.write('200 - OK.');
    res.end();
  }, 3 * 10);

});

app.listen(3000);

